### ISSUE TITLE
The README could provide clearer instructions on how to run the katrina case

### ISSUE THREAD

**Issue by hanschen** [myying/PSU_WRF_EnKF#9]
The current README:

    A sample configuration file has been setup for the Katrina case: config/katrina_enkf

    Test case data set can be found here: http://hfip.psu.edu/yxy159/katrinaTestData.tar

    Once you completed steps 1 and 2, set DATA_DIR to the test data directory, then just submit/execute run_cycle.sh.

But there are no steps 1 and 2.

Given that most people start learning about the system by running the katrina case, it could be worth improving these instructions (for anyone who's motivated).

**Comment by myying** [comment]
the katrina case is not working now that stampede is upgraded.
